name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          
      - name: Grant Permission to Execute
        run: chmod +x gradlew
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build koverXmlReportDebug --stacktrace
        
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: permission-flow/build/coverageReport/report.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
